# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'help.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
  def setupUi(self, Dialog):
    Dialog.setObjectName("Dialog")
    Dialog.resize(399, 334)
    self.label = QtWidgets.QLabel(Dialog)
    self.label.setGeometry(QtCore.QRect(10, 10, 75, 20))
    font = QtGui.QFont()
    font.setPointSize(18)
    self.label.setFont(font)
    self.label.setObjectName("label")
    self.label_2 = QtWidgets.QLabel(Dialog)
    self.label_2.setGeometry(QtCore.QRect(10, 20, 381, 311))
    self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
    self.label_2.setObjectName("label_2")

    self.retranslateUi(Dialog)
    QtCore.QMetaObject.connectSlotsByName(Dialog)

  def retranslateUi(self, Dialog):
    _translate = QtCore.QCoreApplication.translate
    Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
    self.label.setText(_translate("Dialog", "Ayuda"))
    self.label_2.setText(_translate("Dialog", "Los pasos para utilizar esta calculadora son: \n"
"1. Ingrese la función de interés siguiendo el \n"
"formato simbólico de python.\n"
"2. Ingrese un intervalo que desee observar de la \n"
"función, después de ingresado al lado derecho se \n"
"desplegará una vista del gráfico de la función en \n"
"el intervalo de interés.\n"
"3. Proceda a elegir un método de solución.\n"
"4. Según el método que seleccionara se habilitará \n"
"el input de valor inicial o intervalo inicial, por \n"
"favor proceda a ingresarlo.\n"
"5. Presione en calcular para ver su resultado."))
